color: cyan
fieldLayouts:
  44049d79-fbc3-4579-b3fd-c1681adbb983:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-27T18:05:34+00:00'
            elementCondition: null
            fieldUid: cd76630d-2a1f-4191-a23c-b6fb4a98b299 # Left Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52e86f7c-bd61-43ad-b5b3-4593737e1e50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T18:05:34+00:00'
            elementCondition: null
            fieldUid: d8c6811b-3b41-4c1e-91ce-c158325c180b # Right Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a40d9fe2-6d7e-40f1-83ce-c0d35f93727d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T18:05:34+00:00'
            elementCondition: null
            fieldUid: d8c6811b-3b41-4c1e-91ce-c158325c180b # Right Image
            handle: rightImage2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21c37c82-4278-4ab1-b9cf-abe2d3a81d32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf968db5-9cd8-4e8e-bf61-0f407ff5e549
        userCondition: null
handle: imageGrid
hasTitleField: false
icon: objects-column
name: 'Image Grid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
