color: emerald
fieldLayouts:
  df054b61-e81a-4ca8-8dd4-509a4a318142:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T16:15:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a71b232d-801b-4f7e-96c8-6847e135eef5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T16:32:02+00:00'
            elementCondition: null
            fieldUid: 3d587b2b-01d4-4c93-b40e-a7a4beb9cbea # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 484ead20-40e0-435a-bc33-700ac8d30c05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T16:35:03+00:00'
            elementCondition: null
            fieldUid: 74319a6d-ad9d-4794-a29d-efcd9c93164f # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62be3b47-6ca9-4ee0-9f19-bf61e825db2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T16:36:31+00:00'
            elementCondition: null
            fieldUid: 708ff6a5-1f94-412d-ba33-2a3a5a1b13a0 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc28d7b9-7d10-416d-9b0c-7cc667b149c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T17:56:19+00:00'
            elementCondition: null
            fieldUid: 5179e2b3-47aa-4112-97d3-3a9f9f47a9b6 # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bea10171-2fa8-4e6c-83df-6f265a62854b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ebed29e-236c-4b86-9d31-8b7ce7b893ed
        userCondition: null
handle: study
hasTitleField: true
icon: book
name: Study
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
