altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b742c110-d479-4c0d-9e4b-e244efb6b287:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-26T20:10:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 28b12e54-2b54-41e5-9f27-3626e2aea6bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61aab07e-4c75-4d29-950d-ae0605257630
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: images
