columnSuffix: null
handle: subtitle
instructions: null
name: Subtitle
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 8a149362-40c0-4c41-b8c2-bc9d7995c9a6 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
