dateModified: 1742387048
email:
  fromEmail: tim.hamilton6@gmail.com
  fromName: 'Tim Hamilton'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    99010fdf-2b30-456d-b000-880c005acbd7: 'Tim Hamilton' # Tim Hamilton
    e3278a27-f5d2-4e3d-ab9a-40a4380833ab: 'Tim Hamilton' # Tim Hamilton
system:
  edition: solo
  live: true
  name: 'Tim Hamilton'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
